name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint code base
        run: pnpm run lint
      - name: Lint test files
        run: pnpm run test:lint
      - name: Run tests
        run: pnpm run test:coverage
      - name: Check types
        run: pnpm run type-check
      - name: Build the project
        run: pnpm run build
