name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code base
        run: npm run lint
      - name: Lint test files
        run: npm run test:lint
      - name: Run tests
        run: npm run test:coverage
      - name: Check types
        run: npm run type-check
      - name: Build the project
        run: npm run build
